name: Demo to create automatic PR

on:
  push:
    branches:
      - vasagirisai-pr-1

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR 1
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "main"
          base: vasagirisai-pr-1
          title: "demo for auto pr1"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          reviewer: vasagirisai
          token: ${{ secrets.GITHUB_TOKEN }}
