name: Create PR

on:
  push:
    branches:
      - vasagirisai-pr-1

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'This is testing PR'
        body: 'This is testing PR body'
        head: vasagirisai-pr-1
        base: main
