name: Pull Request Action
on:
  push:
    branches:
      - vasagirisai-pr-1

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Updates to main branch'
          title: 'Update to main branch'
          body: 'This pull request updates the main branch with the latest changes.'
          labels: 'update, main'
          reviewers: 'vasagirisai'
          assignees: 'vsagirisai'
          branch: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
